name: static analysis

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    permissions:
      contents: write
    uses: Jubeki/laravel-github/.github/workflows/static-analysis.yml@static-analysis-workflow
